[tool.poetry]
name = "claw"
version = "0.1.0"
description = ""
authors = ["Caleb Bassi <calebjbassi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
google-cloud-speech = "^1.2"
pyaudio = "^0.2.11"
appdirs = "^1.4"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
claw = 'claw:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
